name: GCS Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    # This workflow contains a single job called "deploy"
    runs-on: ubuntu-latest

    steps:
    # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_email: ${{ secrets.GCP_PUSH_BUCKET_EMAIL }}
        service_account_key: ${{ secrets.GCP_PUSH_BUCKET_KEY }}
        project_id: dotted-banner-448417-n1

    # Deploy via GCS: Sync files (update, add, and delete files)
    - name: Deploy via GCS
      run: |
        gsutil -m rsync -r -d . gs://resturent_nyc_dataset/
