name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_KEY }}
        project_id: dotted-banner-448417-n1

    - name: Upload files to GCS
      run: |
        gsutil -m rsync -r ./local-folder gs://resturent_nyc_dataset/
