name: GCS Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: gcp-cloud-dataengineer-project

    # Deploy files to GCS
    - name: Deploy files to GCS
      run: |
        # Remove existing files in the bucket
        gsutil -m rm -r gs://github-action-gcs/* || echo "Warning: Failed to delete objects"

        # Copy files to the bucket
        gsutil -m cp -r * gs://github-action-gcs/
      env:
        CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
