name: GCS Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Authenticate with Google Cloud using the service account
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_PUSH_BUCKET }}

    # Verify the authentication
    - name: Verify gcloud Auth
      run: |
        gcloud auth list
        gcloud config list project

    # Deploy files to GCS
    - name: Deploy files to GCS
      run: |
        # Remove existing files in the bucket
        gsutil -m rm -r gs://resturent_nyc_dataset/* || echo "Warning: Failed to delete objects"

        # Copy files to the bucket
        gsutil -m cp -r * gs://resturent_nyc_dataset/
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_PUSH_BUCKET }}
        CLOUDSDK_CORE_PROJECT: dotted-banner-448417-n1
